"""phase4 invoices table

Revision ID: 00b7b637e518
Revises: 481fa93c1e54
Create Date: 2026-08-23 23:13:40.440117
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b7b637e518'
down_revision: str | None = '481fa93c1e54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_ref', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=512), nullable=True),
    sa.Column('customer_phone', sa.String(length=512), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'paid', 'written_off', name='invoice_status', native_enum=False, length=40), nullable=False),
    sa.Column('has_active_risk', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_ref'), 'invoices', ['invoice_ref'], unique=False)
    op.create_index(op.f('ix_invoices_merchant_id'), 'invoices', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_merchant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_ref'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
