"""phase1 core schema

Revision ID: 481fa93c1e54
Revises: 
Create Date: 2026-08-22 23:48:04.922289
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '481fa93c1e54'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('audit_events',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_merchant_id'), 'audit_events', ['merchant_id'], unique=False)
    op.create_table('dnc_entries',
    sa.Column('dnc_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_identifier', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('dnc_id')
    )
    op.create_index(op.f('ix_dnc_entries_customer_identifier'), 'dnc_entries', ['customer_identifier'], unique=False)
    op.create_index(op.f('ix_dnc_entries_merchant_id'), 'dnc_entries', ['merchant_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('gateway', sa.Enum('razorpay', 'stripe', 'cashfree', 'synthetic', name='gateway', native_enum=False, length=40), nullable=False),
    sa.Column('gateway_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.Enum('payment_failed', 'payment_captured', 'checkout_created', 'checkout_abandoned', 'subscription_charged', 'subscription_halted', 'mandate_confirmed', 'mandate_rejected', 'mandate_debited', 'invoice_overdue', name='event_type', native_enum=False, length=40), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=True),
    sa.Column('customer_phone', sa.String(length=512), nullable=True),
    sa.Column('customer_email', sa.String(length=512), nullable=True),
    sa.Column('payment_method', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_description', sa.String(length=512), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_payment_events_customer_id'), 'payment_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_events_error_code'), 'payment_events', ['error_code'], unique=False)
    op.create_index(op.f('ix_payment_events_gateway_event_id'), 'payment_events', ['gateway_event_id'], unique=False)
    op.create_index(op.f('ix_payment_events_merchant_id'), 'payment_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_events_received_at'), 'payment_events', ['received_at'], unique=False)
    op.create_table('promises_to_pay',
    sa.Column('ptp_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('invoice_id', sa.String(length=128), nullable=True),
    sa.Column('promised_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=False),
    sa.Column('logged_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'kept', 'broken', 'partial', name='ptp_status', native_enum=False, length=40), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('ptp_id')
    )
    op.create_index(op.f('ix_promises_to_pay_customer_id'), 'promises_to_pay', ['customer_id'], unique=False)
    op.create_index(op.f('ix_promises_to_pay_merchant_id'), 'promises_to_pay', ['merchant_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('risk_event_id', sa.Uuid(), nullable=False),
    sa.Column('payment_event_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_type', sa.Enum('payment_degradation', 'checkout_abandonment', 'subscription_failure', 'b2b_receivable', 'mandate_retry', name='workflow_type', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('detected', 'in_progress', 'recovered', 'unrecovered', 'escalated', 'suppressed', name='risk_status', native_enum=False, length=40), nullable=False),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['payment_event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('risk_event_id')
    )
    op.create_index(op.f('ix_risk_events_detected_at'), 'risk_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_risk_events_merchant_id'), 'risk_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_events_payment_event_id'), 'risk_events', ['payment_event_id'], unique=False)
    op.create_index(op.f('ix_risk_events_status'), 'risk_events', ['status'], unique=False)
    op.create_index(op.f('ix_risk_events_workflow_type'), 'risk_events', ['workflow_type'], unique=False)
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('risk_event_id', sa.Uuid(), nullable=False),
    sa.Column('root_cause_category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning_chain', sa.Text(), nullable=True),
    sa.Column('evidence_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_intervention_class', sa.String(length=64), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('llm_prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('output_token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.risk_event_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_diagnoses_risk_event_id'), 'diagnoses', ['risk_event_id'], unique=False)
    op.create_table('intervention_plans',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('risk_event_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('retry_payment', 'send_payment_link', 'send_card_update', 'offer_emi', 'send_mandate_relink', 'send_invoice_reminder', 'send_payment_plan', 'waive_late_fee', 'schedule_retry', 'generate_voice_script', 'trigger_ivr_call', 'escalate_human', 'flag_write_off', 'suppress', name='action_type', native_enum=False, length=40), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', 'ivr', 'internal_retry', name='channel', native_enum=False, length=40), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_content', sa.String(length=8192), nullable=True),
    sa.Column('attribution_window_hours', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'executing', 'completed', 'failed', 'cancelled', name='plan_status', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.risk_event_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_intervention_plans_diagnosis_id'), 'intervention_plans', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_intervention_plans_risk_event_id'), 'intervention_plans', ['risk_event_id'], unique=False)
    op.create_table('outbox',
    sa.Column('outbox_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', 'ivr', 'internal_retry', name='outbox_channel', native_enum=False, length=40), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=8192), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'bounced', 'read', name='outbox_status', native_enum=False, length=40), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['intervention_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('outbox_id')
    )
    op.create_index(op.f('ix_outbox_created_at'), 'outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_merchant_id'), 'outbox', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_outbox_plan_id'), 'outbox', ['plan_id'], unique=False)
    op.create_table('recovery_records',
    sa.Column('recovery_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('risk_event_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('recovered', 'unrecovered', 'partial', 'bounced', 'dnc_hit', 'stopped', name='recovery_outcome', native_enum=False, length=40), nullable=False),
    sa.Column('recovered_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('payment_event_id_recovered', sa.Uuid(), nullable=True),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('recovery_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_event_id_recovered'], ['payment_events.event_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['intervention_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.risk_event_id'], ),
    sa.PrimaryKeyConstraint('recovery_id')
    )
    op.create_index(op.f('ix_recovery_records_plan_id'), 'recovery_records', ['plan_id'], unique=False)
    op.create_index(op.f('ix_recovery_records_risk_event_id'), 'recovery_records', ['risk_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_records_risk_event_id'), table_name='recovery_records')
    op.drop_index(op.f('ix_recovery_records_plan_id'), table_name='recovery_records')
    op.drop_table('recovery_records')
    op.drop_index(op.f('ix_outbox_plan_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_merchant_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_created_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_intervention_plans_risk_event_id'), table_name='intervention_plans')
    op.drop_index(op.f('ix_intervention_plans_diagnosis_id'), table_name='intervention_plans')
    op.drop_table('intervention_plans')
    op.drop_index(op.f('ix_diagnoses_risk_event_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_risk_events_workflow_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_status'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_payment_event_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_merchant_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_detected_at'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_promises_to_pay_merchant_id'), table_name='promises_to_pay')
    op.drop_index(op.f('ix_promises_to_pay_customer_id'), table_name='promises_to_pay')
    op.drop_table('promises_to_pay')
    op.drop_index(op.f('ix_payment_events_received_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_merchant_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_gateway_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_error_code'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_customer_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_dnc_entries_merchant_id'), table_name='dnc_entries')
    op.drop_index(op.f('ix_dnc_entries_customer_identifier'), table_name='dnc_entries')
    op.drop_table('dnc_entries')
    op.drop_index(op.f('ix_audit_events_merchant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('merchants')
    # ### end Alembic commands ###
